### ISSUE TITLE
Password reset email subject should mention bioconductor.

### ISSUE THREAD

**Issue by DarwinAwardWinner** [Bioconductor/legacy.support.bioconductor.org#1]
I just claimed my account via password reset, and the email subject header was "[biostar] Password Reset E-mail". I think that "biostar" should probably replaces with "Bioconductor Support" or something.

**Comment by dtenenba** [comment]
Changed [biostar] to [bioc].

**Comment by Natay** [comment]
Merged fix in commit 844428e
