### ISSUE TITLE
back button scrolls to top of previous page

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/legacy.support.bioconductor.org#10]
If you scroll down the list of posts (https://support.bioconductor.org/t/Latest/) and then click on a post, and then hit the back button, you'd expect it to be scrolled to where you were when you click on a post, but it is scrolled to the top, making it tedious to find where you were and read posts in sequence.

**Comment by vobencha** [comment]
This is working for me. I believe it was fixed.
