### ISSUE TITLE
Suggestions for posting guide

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/legacy.support.bioconductor.org#11]
The posting guide currently reads a bit as a email/Biostar mix, matching advices when using email (include the maintainer of the package in the email) and the new support site (tags). I think it is a bit confusing at times and could benefit from clearly separating general Biostar help, devel email points and common advises. 

For the support site, one could recommend to 
- make use of code formatting to improve readability and attract responses (*)
- don't forget to up-vote questions, answers and comments and accept answers; this is how useful things pop up and avoid/reduce duplicates

(*) note that think I saw posts using back ticks are code delimiters as for markdown syntax (see issue #5); it might be helpful to provide some help on that, amd maybe a youtube video?

**Comment by dtenenba** [comment]
Thanks for the suggestions. BTW, you are welcome to fork and submit a pull request:

https://github.com/Bioconductor/bioconductor.org/blob/master/content/help/support/posting-guide.md

**Comment by lgatto** [comment]
Oh, did not know about that repo! Will try to make a helpful contribution.

**Comment by lshep** [comment]
Closing this -  feel free to pull request to the website if you think further changes should be made
