### ISSUE TITLE
Messages about own posts

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/legacy.support.bioconductor.org#16]
Is it possible to avoid receiving messages for one own posts?

**Comment by dtenenba** [comment]
Hmmm....believe it or not, we consider this a feature. Biostar doesn't send messages for one's own posts by default, but we changed it so that it would, to make the behavior more like a mailing list. Maybe we'll discuss this internally and see what people think.

**Comment by liz-is** [comment]
I would also prefer not to receive messages telling me about my own posts.

**Comment by lshep** [comment]
Currently leaving as is -  if there is enough of a request we will consider chaning but we do consider this a useful feature
