### ISSUE TITLE
Tags for packages with long names

### ISSUE THREAD

**Issue by mikelove** [Bioconductor/legacy.support.bioconductor.org#17]
I tried to add 'GenomicAlignments' as a tag to a post, and got this message:

`Tag line is too long (50 characters max)
Choose one or more tags to match the topic. To create a new tag just type it in and press ENTER. Be sure and include the names of any relevant Bioconductor packages.`

**Comment by ghost** [comment]
This sounds like an issue to mention to @ialbert and probably requires a schema change to fix? @mikelove, can you tell us the post URL?

**Comment by mikelove** [comment]
Here's the post. To clarify, the sum of the number of characters of all tags looks like it needs to be < 51.

https://support.bioconductor.org/p/edit/62966/

**Comment by ialbert** [comment]
That particular check can be overriden here

https://github.com/ialbert/biostar-central/blob/master/biostar/apps/posts/views.py#L46

the database can take up to 100 characters - this was there to try to enforce shorter and fewer tags. We found that the utility of tags decreases as there are more of them - on the other hand sometimes people want to be more thorough.
