### ISSUE TITLE
Post formatting is lost upon editing.

### ISSUE THREAD

**Issue by DarwinAwardWinner** [Bioconductor/legacy.support.bioconductor.org#2]
I tried editing this post: 

https://stat.ethz.ch/pipermail/bioconductor/2014-July/060525.html

Initially, in the Biostar system, it had the same formatting as the mail message. But when I clicked the edit button, all the line breaks were gone from the edit box, and when I clicked save, everything was jumbled into one big line. You can see the result after editing here:

https://support.bioconductor.org/p/60513/#60514

**Comment by dtenenba** [comment]
I think I'm going to pass this one along to the author of biostar (who has said he's pretty busy, so it may not get fixed quickly). 

I've filed https://github.com/ialbert/biostar-central/issues/262

**Comment by ialbert** [comment]
Answer is here https://github.com/ialbert/biostar-central/issues/262

**Comment by ialbert** [comment]
The issue has been fixed. see the above ticket.
