### ISSUE TITLE
search throws error and dumps DEBUG output on live web site

### ISSUE THREAD

**Issue by fschwach** [Bioconductor/legacy.support.bioconductor.org#27]
I'm sure you are already aware of this but just in case. I just tried a few times to use the search functionality on the live web site and it throws this:

ProtocolError at /local/search/page/

('Connection aborted.', error(111, 'Connection refused'))

Request Method:     GET
Request URL:    https://support.bioconductor.org/local/search/page/?q=Error+in+do.call
Django Version:     1.6.5
Exception Type:     ProtocolError
Exception Value:    

('Connection aborted.', error(111, 'Connection refused'))

Exception Location:     /home/www-data/.virtualenvs/biostarsenv/lib/python2.7/site-packages/pyelasticsearch/client.py in send_request, line 281
Python Executable:  /usr/bin/python
Python Version:     2.7.6
Python Path:    

['/home/www-data/.virtualenvs/biostarsenv/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/www-data/biostar-central',
 '/home/www-data/biostar-central/biostar',
 '/']

Server time:    Wed, 2 Sep 2015 05:54:06 -0700

**Comment by dtenenba** [comment]
Yes, thanks we are aware of it and working on the issue. Should be ok for the time being.
