### ISSUE TITLE
Users often do not use Styles dropdown to format code

### ISSUE THREAD

**Issue by mikelove** [Bioconductor/legacy.support.bioconductor.org#28]
A suggestion on the New Post page on how to highlight R code/output might help.

https://support.bioconductor.org/p/new/post/

Code formatting really helps to see what's going on.

**Comment by b-long** [comment]
Hi Mike,

Sorry for the slow reply.  We agree!  Code formatting certainly improves the quality of a question on the site :+1:  I've made a change to the website to address your concern and you should be able to see it at : https://support.bioconductor.org/p/new/post/ , just above the text area to enter content.

The changeset , if you're interested is here: https://github.com/Bioconductor/support.bioconductor.org/pull/29 .

Thanks for the feedback :smile:

**Comment by mikelove** [comment]
thanks Brian!

on the FAQ, instead of:

> Click the "Format" drop down (at the top of the text area) to select a different paragraph 
> format and choose "Formatted" to render the text using a fixed-width font

I would say:

Click the "Styles" drop down (at the top of the text area) to select a different text style
and choose either "Code" under Block Styles for code blocks or "Inline Code"
under Inline Styles for inline code.

**Comment by b-long** [comment]
Mike, 
Great point, I really like the text you've suggested :+1:  I've modified the FAQ, per your suggestion to the text.

\- Brian
