### ISSUE TITLE
RSS not working

### ISSUE THREAD

**Issue by malcook** [Bioconductor/legacy.support.bioconductor.org#3]
RSS feeds are ill-formedm as listed at https://support.bioconductor.org/info/rss/

example,
https://support.bioconductor.org/feeds/latest/

(at least as far as feedly RSS reader is concerned - I did not look into details)

**Comment by dtenenba** [comment]
Hmmm...I'm consuming the same feed with some ruby code and it works for me. I also went to feedly.com and pasted in that url it seemed to work, I got no error. Can you list the exact steps that led to your error?

**Comment by malcook** [comment]
Hmmm - 2nd time is the charm.  It works for me now.  What I tried both times was pasting 

https://support.bioconductor.org/feeds/latest/

into feedly's "searh or add feed" box on the home page.

So, I will 'close' this issue.

Sorry gang.
