### ISSUE TITLE
'ADD COMMENT' button easy to miss

### ISSUE THREAD

**Issue by mikelove** [Bioconductor/legacy.support.bioconductor.org#31]
For the posts I answer, it is most common that users ignore the small blue-on-grey "ADD COMMENT" button or "ADD REPLY" button and instead use the large green "Add Answer" button.

So they end up adding Answer, when they are really want to respond to an Answer, and so the site doesn't really benefit from threading.

I'd suggest making these buttons (add comment / add reply) be larger and have brighter colors to compete visually with "Add Answer".

Note that the "Add Answer" button is used most often by regular visitors to the support site (developers) while the "Add Comment" / "Add Reply" buttons should be aimed at the new visitors, so we should make it easier for them to spot.

**Comment by mikelove** [comment]
hi! thanks for looking into this (i see the bigger font this morning). this should help a lot, and threading will make discussions a lot easier to follow. i'll pay attention to see if people use the replies/comments more now.

**Comment by dtenenba** [comment]
It's also a more noticeable (hopefully) color scheme.

**Comment by mikelove** [comment]
Just some feedback. Thanks again for the attention to this.

It seems the use of comment / reply for my users has gone from ~10% to ~50%. So it's better, but the open text box and green answer button is still very popular for follow-up comments/replies.

**Comment by dtenenba** [comment]
Do you have a specific suggestion?

**Comment by mtmorgan** [comment]
Some progress, then. On my screen one has to aggressively scroll to the bottom to see the Add your answer and green button, so it's surprising that it's so attractive.

Maybe changing 'Add your answer' to 'New Answer' would make it clearer?

More ambitiously, require that the new 'New Answer' be clicked before the text entry box appears? I don't know how complicated that would be (and it would pull the New Answer button more into the field of view, so might actually be counter-productive?).

Martin

**Comment by mikelove** [comment]
Yes, I agree that the green Add Answer button might not even come into play, because people see the text box and start writing before they've even scrolled all the way down.

So here is the current layout, where the OP could show up and choose between answer and comment.

![screen shot 2016-03-25 at 12 11 19 pm](https://cloud.githubusercontent.com/assets/69203/14048147/bbe0cd0c-f282-11e5-9494-361b8a0bfecd.png)

---

Here is one proposal, just to make these buttons much more obvious (and easier to try out than hiding the text entry box)

![screen shot 2016-03-25 at 12 11 19 pm](https://cloud.githubusercontent.com/assets/69203/14048321/e477e04c-f283-11e5-8439-670fa06c9c72.png)

I don't think it would become a problem with devels accidentally adding comments instead of answers.

**Comment by mikelove** [comment]
I came with some empirical data: of the past 16 times when the OP replied to my answer, 7 times they used the Add Answer button, and 9 times they used the Add Comment button.

So I think the Add Comment / Add Reply buttons still need to have more visual prominence and we should consider hiding the text box for Add Answer so that it only pops up after the click.

What I've been doing is reminding people how to use the site, but it's always a stream of new users so it feels a bit like Sisyphus rolling the ball up the hill. When people start voting on answers, and then they get out of temporal order it becomes difficult to figure out what's going on.

**Comment by mtmorgan** [comment]
Two other things might play into this -- I think users need some minimal level of reputation to do things, maybe commenting is one? and when one replies via email the reply is assigned somewhere, maybe an 'answer' by default? These are speculations that I haven't had a chance to investigate...

**Comment by mikelove** [comment]
re: email. I've replied via email before to comments and to answers and IIRC it gets added properly (that is, as a child node of whatever I was responding to)

**Comment by mikelove** [comment]
Just re-pinging this thread. 

As a heavy user of the support site, I want to report that the great majority of (my) users continually “Answer” their own post for follow up questions, so the subtle text above the form input is not working.

It means I always have to moderate these, to move them to comments, which is a tedious. If I don’t, the temporal flow of conversation is broken by voting.

I do think my design suggestions above would help. Or you could do more intensive coding like disabling “answering” one’s own post.

Also Martin’s suggestion of “New answer” would probably help, along with a less visually prominent button. Developers will still find it, because they use the site often.

**Comment by schifferl** [comment]
I have been working on a fix with @lshep and think this issue will essentially be resolved with the merging of my pull request. For a demo see [184.72.110.235](184.72.110.235) where you can login and click around. There will be some warnings about https, click through those and then change your password later using the real support site. Questions, comments, or feedback welcome – just sooner rather than later because I will have time to make changes today. Thanks, Lucas

**Comment by mikelove** [comment]
I just checked out this, it is perfect. 

Turning the _comment_ and _reply_ links green and hiding the _answer_ option behind the click will really help out. 

Thanks for your work @schifferl and @lshep!

**Comment by seandavi** [comment]
I think it is definitely worth a try. Just a couple of thoughts (not requests!!!). Is it worth doing A/B testing based on user? Is this a permanent change, or should it be announced as a "trial" with some approach to define via user feedback or metrics the decision to keep?

**Comment by schifferl** [comment]
My thoughts are that this probably needs to be a permanent change and that A/B testing likely isn't necessary. It seems that the problem of posting an answer instead of a comment or a reply is rather pervasive (I am guilty of this too) and if the pull request is the anodyne for the issue then we go ahead and make the change permanent. Otherwise, if users balk, we can always revert the change.

**Comment by seandavi** [comment]
Good with me. Just asking. And thanks a bunch for doing this.

**Comment by lshep** [comment]
Lucas's changes have been merged -  further comments welcome.

**Comment by jmacdon** [comment]
The Add Answer link doesn't work on Firefox. The ADD COMMENT and ADD REPLY buttons do.

![image](https://user-images.githubusercontent.com/5940924/40003401-3b9d9f76-5761-11e8-8a8a-2b01449cca34.png)

**Comment by schifferl** [comment]
Perhaps related to running the script inline, I will have this fixed momentarily.

**Comment by schifferl** [comment]
Merging pull request #46 will fix the Firefox issue : )

**Comment by lshep** [comment]
@jmacdon   @schifferl patch is now live on the site -  please try again.

**Comment by jmacdon** [comment]
Works for me now. Thanks Lori!

**Comment by lshep** [comment]
Thanks to @schifferl !

**Comment by schifferl** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/c74e9d0f-f741-4a71-88eb-8a66a55199a6-29a17361-ffb4-4d0e-969f-f07dcc99916d-v1.png?transparent=1&palette=1&width=246)

**Comment by gksmyth** [comment]
Thanks to Mike Love for raising this issue, which I have found similarly frustrating.

One has to ask why this problem hardly ever occurs on other web forums or indeed on the original biostars.org site of which Bioc Support is a fork. One could argue that Bioc users are less likely to be computer science savvy than those on Biostars, but it's hard to argue why Bioc users should be less able than readers of almost any other forum.  I suspect the main reason for Biostars' better behaviour is that, on the Biostarts website, the "Add your answer" dialog box is framed within a larger shaded box that makes it appear visually separate from the answers above. On the Bioc Support site, the "Add your answer" box just floated in white space, making it appear connected to the answer above it.

Users almost never answer their own questions on the statistics forum https://stats.stackexchange.com even though "add a comment" is in much smaller font than "Your Answer". The secret here perhaps is that the answer dialog box is the only non-shaded part of the screen, which again makes it visually separate from the answer above it.

So I don't think the secret is the size of fonts or colours of buttons. Making the "Add comment" and "Add reply" buttons large and bright mainly adds visual noise to the page. I think the secret is rather in ensuring clear visual separation between the answer text box and the existing answer above it. It needs to look like a separate yard.

I see that, starting today, there is no "Add your answer" dialog box on Bioc Support until "Add Answer" is clicked on. Thanks, hopefully that will improve things although, to my eyes, Bioc Support still doesn't properly separate the answer box from the rest of the thread. I find the stats.stackexchange design less cluttered, and I think the Biostars solution would also have been worth a try.
