### ISSUE TITLE
Awarding of badges not working 

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/legacy.support.bioconductor.org#34]
I'm sure someone else has noticed this already, but the awarding of the badges on the support site is out of date. The last badge was awarded (to me) 8 months ago; but there are many more recent posts that should warrant an award (e.g., "Scholar" for https://support.bioconductor.org/p/90591/) and have not gotten one. I personally was looking forward to getting the "Cylon" badge when I passed the 10k reputation mark, but this never eventuated. I recall that the same problem happened some time ago, but I can't remember how @dtenenba fixed it.

**Comment by lshep** [comment]
Thank you for making us aware of this issue. We will look into resolving.

**Comment by lshep** [comment]
We believe we have resolved the issue. Badges should be awarded now. 

We restarted celery script in crontab.

**Comment by mtmorgan** [comment]
@lshep I don't think this is fixed, badges have not been awarded for quite a while, for instance 10 months ago for https://support.bioconductor.org/b/6/

**Comment by lshep** [comment]
I look into this again.

**Comment by lshep** [comment]
I think this is corrected with the latest updates
