### ISSUE TITLE
Tags stats through the API

### ISSUE THREAD

**Issue by llrs** [Bioconductor/legacy.support.bioconductor.org#36]
I would like to have stats about the support site by month. Specially I am interested in questions about packages (Which I will restrict to questions properly tagged).  Is it possible to query for tags and get the list of posts with said tag?

I tried several url but neither of them worked:
```
https://support.bioconductor.org/api/tag/limma/
https://support.bioconductor.org/api/tags/limma/
https://support.bioconductor.org/api/t/limma/
```
My only solution is to iterate through post (by checking last post id added) and keep the tags and dates of all of them.  I don't know how are the numbers for the shields of the packages calculated but that would be another option (I assume that would be quicker than my proposed solution).

**Comment by mtmorgan** [comment]
The only public api is as documented at https://support.bioconductor.org/info/api/ . There is also https://support.bioconductor.org/t/limma . The badges are created by directly querying the SQL tables. If you'd like a dump of the creation date / tag table, I can provide that (but would not be willing to do this often). The result would be a CSV file with information like
```
         creation_date         |                             tag_val                              
-------------------------------+------------------------------------------------------------------
 2017-06-27 16:58:50.887153+00 | ChIPQC
 2017-06-27 16:18:14.577691+00 | plotMutationSpectrum,somaticsignatures,somaticsignatures package
 2017-06-27 15:38:46.09732+00  | GRanges,cn.mops
 2017-06-27 13:37:35.243739+00 | chipseq,BCRANK
 2017-06-27 12:59:12.086359+00 | limma,camera,mroast,tximport
 2017-06-27 09:29:20.376981+00 | makecdfenv,bioclite
 2017-06-27 09:09:33.728853+00 | cn.mops
 2017-06-27 08:31:07.946362+00 | R
 2017-06-27 07:49:10.799601+00 | affxparser,cdf,hta2.0
 2017-06-27 07:32:08.735279+00 | dnastringset,list,stringset
```

**Comment by llrs** [comment]
Thanks Martin

I will use my slow method and store the data locally. I'll try to avoid abusing the api. giving 1 second pause every 1000 queries. If that way I don't succeed I might ask for help.
