### ISSUE TITLE
Total amount of post at a given date

### ISSUE THREAD

**Issue by llrs** [Bioconductor/legacy.support.bioconductor.org#37]
When looking information from a date using the [api](https://support.bioconductor.org/info/api/) it returns a list with:

>  - answers: total number of answers as of the given date.
>  - comments: total number of comments as of the given date.
>  - questions: total number of questions as of the given date.

However it is impossible to know the id of the last post. Because jobs, news and tutorials  aren't grouped and the total amount of posts are not returned. 

Could it be changed to return the total amount of post for each type, or/and the total amount of posts for the given date?

The reason I run into this issue is because I want to know the last question posted. I thought I could look at the current day add all the posts in answers, comments and questions, and start looking around that post id (31775 + 33833 + 30889=96497). However there are many news and jobs accumulated over the years ((One of the latest updated question id is 98048) which makes it harder to query for the latest question. 

Many thanks

**Comment by mtmorgan** [comment]
The date uri returns a list of posts for the day; the post uri includes the type of post

```
stats <-
    function(year="2017", month="07", day="12")
{
    url <- paste(
        "https://support.bioconductor.org/api/stats/date",
        year, month, day,
        sep="/"
    )
    content(GET(url))
}

post <-
    function(post)
{
    url <- paste(
        "https://support.bioconductor.org/api/post",
        post,
        sep="/"
    )
    content(GET(url))
}        

s <- stats()
post(s$new_posts[[ length(s$new_posts) ]])$type
```
