### ISSUE TITLE
CEMiTool Error

### ISSUE THREAD

**Issue by rajasundaramn** [Bioconductor/legacy.support.bioconductor.org#40]
Hi,

I am trying to run gene co-expression analysis using CEMiTool package on a dataset that is available in GEO. I created a data frame with genes as rows, samples as columns and the body contains gene expression. The annotation file (attached) contains Sample names and the time points of treatment (groups). When I execute my R code, I see the following error:

Error in .local(cem, ...) : 
  Could not specify the parameter Beta. No modules found.
In addition: Warning message:
In pracma::gammainc(bh/x, ah) : Arguments 'x' and/or 'a' are too large.
 
I have attached my R code, the annotation file and the supporting files needed to execute the R code. 

```R code
## Clear workspace
rm(list=ls())

source("https://bioconductor.org/biocLite.R")

# Load the libraries required
library(GEOquery)
library(CEMiTool)
library(openxlsx)

# Downloading GDS datasets from GEO
gse_8539 <- getGEO("GSE8539")

# Create a dataframe with the expression dataset
eset <- gse_8539[[1]]
df_gse8539 <- exprs(eset)

# Select the columns that contain ATP??S treatment values
df_gse8539 <- subset(df_gse8539, select = c(1:8))

# Read the excel file with HEEBO mapping details
df_heebo <- read.xlsx("HEEBO_Human_Set_v1.00.xlsx", sheet = 2, colNames = T)

# Select the Oligo IDs and their gene symbols
df_heebo <- df_heebo[,c("Oligo_ID", "Symbol.v12")]

# Merge the data in df_gse8539 and df_heebo to map the Oligo IDs to gene names
df_gse8539_map <- merge(df_heebo, df_gse8539, by.x = "Oligo_ID", by.y = "row.names", all.y = TRUE)

# Discard duplicate gene entries and calculate the average of the duplicates
df_gse8539_mapped <- aggregate(df_gse8539_map, by=list(Gene_Name = df_gse8539_map$Symbol.v12), FUN=mean)

rownames(df_gse8539_mapped) <- df_gse8539_mapped[,1]
df_gse8539_mapped$Gene_Name <- NULL
df_gse8539_mapped$Oligo_ID <- NULL
df_gse8539_mapped$Symbol.v12 <- NULL

# Read the excel file with annotation details
gse8539_annot <- read.xlsx("GSE8539_annotation.xlsx", sheet = 1, colNames = T)

# Run CEMiTool
# cem_8539 <- cemitool(expr = df_gse8539_mapped)
cem_8539 <- cemitool(expr = df_gse8539_mapped, annot = gse8539_annot)
```

Please let me know how to resolve this issue.

Thanks
Nisha

[GSE8539_annotation.xlsx](https://github.com/Bioconductor/support.bioconductor.org/files/1284694/GSE8539_annotation.xlsx)
[HEEBO_Human_Set_v1.00.xlsx](https://github.com/Bioconductor/support.bioconductor.org/files/1284695/HEEBO_Human_Set_v1.00.xlsx)
![error](https://user-images.githubusercontent.com/31733367/30164457-99733cd0-93aa-11e7-9f54-445f4c994d06.PNG)

**Comment by nturaga** [comment]
@rajasundaramn Please post on support.bioconductor.org
