### ISSUE TITLE
Branch that is running https://support.bioconductor.org/

### ISSUE THREAD

**Issue by nmvega** [Bioconductor/legacy.support.bioconductor.org#41]
Hello Friends:

Could you tell me which GitHub Branch is used for this site?: https://support.bioconductor.org/

Also if subsequent **fixes / updates / changes / improvements** made locally on that server were committed back to that GitHub Branch? (because issues may have been encountered since [e.g. performance, security, etc] and was wondering -- if they were fixed locally -- whether they made it back here).

Thank you in advance. :)
Noelle

**Comment by vobencha** [comment]
The master branch of this repository is the code used for the support site. Development is done on the branch and pulled on the server.

Have you noticed a performance hit or a security issue? If yes, please provide a reproducible example or further explain the problem you're experiencing.

Valerie
