### ISSUE TITLE
markdown in comments

### ISSUE THREAD

**Issue by llrs** [Bioconductor/legacy.support.bioconductor.org#43]
This is related to https://github.com/Bioconductor/support.bioconductor.org/issues/5.

I recently noted that markdown button is not present in comments until the comment is posted and then edited. Is this a bug or a feature? I would expect to be able to write from the beginning in markdown. 

Also, could the default editing mode be set on the personal settings?

**Comment by LiNk-NY** [comment]
Yes, I don't see the markdown button after clicking on the `ADD COMMENT` button. 
Perhaps @schifferl can have a look at it? 
cc @lshep

**Comment by lshep** [comment]
This should be fixed by the pull request from https://github.com/Bioconductor/support.bioconductor.org/pull/44

**Comment by llrs** [comment]
I'm starting to get paranoid, I posted a comment in [this thread](https://support.bioconductor.org/p/98365/) under this [test](https://support.bioconductor.org/p/98365/#106273) and it seems it disappeared.
![image](https://user-images.githubusercontent.com/6818218/36598168-8f16a4da-18ab-11e8-96e8-dbcc24cfbb43.png)
Now I receive a notification from this issue, I come here and I don't see anything new. Is something going on?
My apologies for my tone in any case

**Comment by lshep** [comment]
I wanted to test it out first before I officially comment -  so I deleted the comment -  but yes it is fixed now.

**Comment by schifferl** [comment]
@lshep could you delete my test post too? And @llrs you should now see markdown in comments, just clear your browser cache if you don't.

**Comment by lshep** [comment]
what test post are you referring to?

**Comment by llrs** [comment]
@schifferl and @lshep  Many thanks! It is working now after deleting the cache.

@lshep The one I linked in my previous comment (I think)

**Comment by schifferl** [comment]
The answer at the bottom of this https://support.bioconductor.org/p/98365/... the one that reads "This is a test"

**Comment by lshep** [comment]
Ok.  I just did.

**Comment by mtmorgan** [comment]
@llrs @schifferl I deleted Luis' post from the support site; I don't think it's appropriate to use the active support site as a 'test' platform.
