### ISSUE TITLE
markdown mode sometimes does not line wrap or format final version correctly

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/legacy.support.bioconductor.org#47]
This https://github.com/Bioconductor/support.bioconductor.org/commit/8bb5b13 seems to have provided line wrapping for some people. It does not for me. Also, if I enter text in markdown mode the line endings are ignored, the post is displayed as if one long line

```
foo

bar
```

becomes `foo bar`. It seems to be a problem with the interpretation of carriage returns entered from the keyboard on my chrome / linux browser; if I copy-paste from emacs line endings are respected. For what it's worth, I have

```
Chromium	66.0.3359.139 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Revision	04f3a687c3f0ca1c1c1444683ddfadb74191b787-
OS	Linux
JavaScript	V8 6.6.346.26
Flash	29.0.0.171 /usr/lib/adobe-flashplugin/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.139 Chrome/66.0.3359.139 Safari/537.36
Command Line	/usr/lib/chromium-browser/chromium-browser --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=29.0.0.171 --enable-pinch --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/chromium-browser/chromium-browser
Profile Path	/home/mtmorgan/.config/chromium/Default
```

**Comment by lshep** [comment]
as a new editor has been implemented I am closing this for now -  Please reopen if this is a continued issue.
