### ISSUE TITLE
Moderate tools busted this morning

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/legacy.support.bioconductor.org#48]
As of this morning (10:30am Australian Eastern Standard Time), the moderator tools aren't working on the Bioc Support site. I can click on the "moderate" button. That opens a dialog as usual, but I can't then "Select moderation option". Clicking on the options doesn't give any response.

It seems an isolated issue because the "edit" button is working correctly.

**Comment by lshep** [comment]
We are looking into this.

**Comment by mtmorgan** [comment]
@schifferl this is a priority, because we cannot easily remove spam posts otherwise.

**Comment by schifferl** [comment]
I am working on this and will have it fixed ASAP.

**Comment by lshep** [comment]
This should be fixed with the above merge from @schifferl  .  Please let us know if there is still an issue
