### ISSUE TITLE
regression: formatting inline code

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/legacy.support.bioconductor.org#49]
The markdown editor now formats `inline code` in serif italic, but should be fixed-width like the code blocks. An example is `memoize` in this comment: https://support.bioconductor.org/p/108995/#109004

**Comment by schifferl** [comment]
Sorry about that, this is related to ascii math markup (see the docs [here](https://docs.mathjax.org/en/latest/start.html#asciimath-input)). Just a configuration issue that I will switch off shortly.

**Comment by schifferl** [comment]
After a bit more investigation I was able to reproduce the behavior shown in the comments. The formatting is related to the fact that the `` ` `` character is treated differently between markdown and the normal editing mode. In the [first comment](https://support.bioconductor.org/p/108995/#109004), the `` ` `` character was used outside of markdown mode and interpreted as AsciiMath input by MathJax. In the [second comment](https://support.bioconductor.org/p/108995/#109071), the `` ` `` character was used in markdown mode and was treated as inline code. Neither behavior was wrong but this might lead to a bit of confusion. Perhaps it would be wise to only allow LaTeX style math (i.e. surrounded by the `$` character). Just let me know and I will modify the configuration.

**Comment by mtmorgan** [comment]
I like the only LaTeX-style math route, to avoid confusion. Thanks for looking in to this!

**Comment by lshep** [comment]
Closing for now  Reopen if this is an issue with the new editor but I think with the markdown always on and MathJax not currently enabled this isn't an issue.  -
