### ISSUE TITLE
markdown code chunk sometimes rendering as math?

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/legacy.support.bioconductor.org#51]
When using markdown mode, I've seen expressions like \`x <- se\` rendered as some odd LaTeX-looking math equation. I've managed to get rid of them by editing my post (again in markdown mode, often just typing the exact same command).

Sorry I don't have a reproducible example at this time, but I thought it worth reporting.

**Comment by LTLA** [comment]
I can second this. It seems to occur when I start typing in the non-markdown mode, and then change my mind and press the "Markdown" button half-way through. Which is unfortunate, as (i) I never remember to press the "Markdown" button before I write any text, and (ii) the resulting code chunks are completely mangled. Inline code gets math'd and code blocks have no line endings (as observed in #47).

**Comment by lshep** [comment]
Looking into it.  We may be making some updates to the editor shortly that should hopefully correct this issue.

**Comment by LTLA** [comment]
Here's a ~nice~ hideous example, as of time of writing: https://support.bioconductor.org/p/113478/#113487

**Comment by lshep** [comment]
hopefully will have a demo with the new editor next week.  We think this stems from a conflict with MathJax - either way we are actively looking into it.

**Comment by lshep** [comment]
Don't think this should be an issue anymore with the new editor -  at least at present
