### ISSUE TITLE
Incorrect entry in NEWS listing

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/legacy.support.bioconductor.org#53]
Clicking on:

https://support.bioconductor.org/t/News/

... gives me a number of entries including:

https://support.bioconductor.org/p/111277/

... which is not really news _per se_, it just has "NEWS" in the title. I presume that the code checks for NEWS-ness based on pattern matching, which is incorrect in this case.

Not really an urgent error, but hey, just so you know.

**Comment by lshep** [comment]
It really isn't an issue -  its based on adding the news tag - we can remove tags that aren't appropriate.

**Comment by LTLA** [comment]
Ah - I see. I didn't realize that creating a NEWS post would automatically add a `news` tag. Apologies.
