### ISSUE TITLE
Question on BioConductor about RSVSim, but no comments or answers.

### ISSUE THREAD

**Issue by FiniDG** [Bioconductor/legacy.support.bioconductor.org#54]
I know this is not the place to ask a question, but you do not seem to give support on the forums, so I ask this here.

How can I make a simple insertion with RSVSim?
from this:
```
width seq                                                                                                                           names               
[1]    40 AAAAAAAAAAAAAAAAAAAATTTTTTTTTTTTTTTTTTTT    chr1
[2]    40 GGGGGGGGGGGGGGGGGGGGCCCCCCCCCCCCCCCCCCCC    chr2
```

to this:
```
width seq                                                                                                                           names               
[1]    32 AAAAAAAAAAAAAAAATTTTTTTTTTTTTTTT                    chr1
[2]    48 GGGGGGGGGGGGGGAAAATTTTGGGGGGCCCCCCCCCCCCCCCCCCCC    chr2
```

And do this 30 times random in the genome (so 30 INS in chr2)

Really, this seems impossible after days of trying. I either get copy from the same chromosome (which makes a DUP, not an INS), a cut in the same chromosome (which gives a DEL as well as an INS), or just random insertions copy/pastes from chr1 --> chr2, chr2 -->chr2, chr1-->chr1 or chr2 --> chr1. Why isn't it possible to just make insertions in 1 chromosome? (using a provided second chromosome, in this case chr1). 

see these 2 posts for further elaboration, and hopefully some answers or extra questions to me there
https://bioinformatics.stackexchange.com/questions/5269/rsvsim-insertions-from-chr1-to-chr2
https://support.bioconductor.org/p/114354/#114523

**Comment by FiniDG-HAN** [comment]
I think I used the thing pasting links not correctly, so here is just a copy/paste version of the links
https://bioinformatics.stackexchange.com/questions/5269/rsvsim-insertions-from-chr1-to-chr2
https://support.bioconductor.org/p/114354/#114523
