### ISSUE TITLE
can not sign up

### ISSUE THREAD

**Issue by xuranw** [Bioconductor/legacy.support.bioconductor.org#55]
Hi,

I did not recieve the comfirmation email for sign-up. What should I do now? Thanks!

**Comment by lshep** [comment]
Did you check your spam and trash folder -  sometimes the confirmation gets flagged as spam

**Comment by xuranw** [comment]
> Did you check your spam and trash folder - sometimes the confirmation gets flagged as spam

I have checked the spam emails and didn't see the confirmation.

**Comment by lshep** [comment]
I do see you in the list of users with the email xuranw@sas.upenn.edu and that the confirmation email tried to send multiple times -  maybe a firewall or some email setting is preventing it from being received on your end?

**Comment by xuranw** [comment]
I'm afraid not. Is there any way that I can access my account?

**Comment by lshep** [comment]
We have tried to verify your account manually.  Please try logging in.

**Comment by xuranw** [comment]
Thank you so much! I have logged in!
