### ISSUE TITLE
Answer header has additional "A:"

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/legacy.support.bioconductor.org#57]
Looking at https://support.bioconductor.org/p/116724/ as an example, we see my answer has:

> Answer: A: Error in installation of scran

We could do without the redundant "A:".

**Comment by lshep** [comment]
Thanks for reporting this - I'll look into it

**Comment by lshep** [comment]
@ialbert   any thoughts on this one?  I can't find anything apparent that adds both  the Answer:  and the A: to the title?  I know the biostars site doesn't have this problem.

**Comment by ialbert** [comment]
The line that adds both Answer and A would come from a construct like this:

https://github.com/Bioconductor/support.bioconductor.org/blob/master/biostar/server/templates/server_tags/post_body.html#L9

this has both `post.get_type_display` and later `post.title` 

the title for an answer is set to be the question prepended with "A: "

the `get_type_display` generates the word representation of the type of the post "Answer" in this case. But this code should only activate when the post is toplevel. Which an answer is not, so your code should not display the title for answers.  Perhaps this is not the code you are running in production.

**Comment by lshep** [comment]
I believe this was one of the templates Dan overwrote in the past so we have our own in the org/bioconductor/...   I'll check what is in there and adjust appropriately but thanks for pointing me to the right direction
