### ISSUE TITLE
tags are difficult to discover

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/legacy.support.bioconductor.org#6]
A less-commonly used tag cannot be found easily on https://support.bioconductor.org/t/; it would be good to have a tag search box (a la StackOverflow), or simply to present all tags on a single page. Tags should probably be presented without their usage embedded "limma", rather than "limma x 1234".

**Comment by dtenenba** [comment]
I added a tag search box. I hesitate to remove the 'x 1234' because I never like to remove information that could be potentially of interest to the user. If you really want me to, I'll try to remove it.....

**Comment by mtmorgan** [comment]
On 09/22/2014 01:37 PM, dtenenba wrote:

> I added a tag search box. I hesitate to remove the 'x 1234' because I never like
> to remove information that could be potentially of interest to the user. If you
> really want me to, I'll try to remove it.....

One possibility is to place it outside the tag [limma] x 2425. Also perhaps the 
tags do not need to be in columns, but just flow, and formatted (same font and 
box size) as on the main page. Also the tag search doesn't really restrict 
search to specific tags, e.g., adfasdf will format the string as a 'tag', but 
I'm not interested in finding an arbitrary string...

Martin

> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bioconductor/support.bioconductor.org/issues/6#issuecomment-56438940.

## 

Computational Biology / Fred Hutchinson Cancer Research Center
1100 Fairview Ave. N.
PO Box 19024 Seattle, WA 98109

Location: Arnold Building M1 B861
Phone: (206) 667-2793
