### ISSUE TITLE
New markdown-based editor is undocumented

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/legacy.support.bioconductor.org#62]
The Bioconductor Support editor was changed a few weeks ago to markdown. From a beginner point of view, the change from wysiwig to a markup language is a huge conceptual change and requires a different style of thinking. Yet there is no documentation on the Bioc Support website to help users with this transition. There wasn't even a NEWS item to announce the change. The FAQ page still describes the old editor.

The new markdown-based editor is making a mess of questions when the user includes R code and output (which we have encouraged them to do!). Any comment line gets converted into a header. Any code line with a prompt gets converted into block quotation. Any other lines get mashed together into an unreadable text paragraph. The upshot is that users can no longer directly cut and paste R code and output into their questions, at least not without a lot of extra editing.

I now find that I have to edit questions to reformat the code in addition to answering the question. I would prefer not to have to keep doing this.

Other support forums that use markdown (like the github site I'm typing this text into now) do have appropriate documentation. Are there plans to implement such documentation for Bioc Support?

It should be kept in mind that most Bioc Support users are not from programming backgrounds. Many are biologists. The typical user who asks a question Bioc Support is often less sophisticated from a programming point of view than an average user of github or similar sites.

**Comment by mtmorgan** [comment]
This sounds like a reasonable request.

For what it's worth, for new questions the user enters their question and then has to scroll past a preview of their question to press the 'Submit' button -- they see the poor formatting, but proceed anyway.

**Comment by gksmyth** [comment]
@mtmorgan The trouble is that there is no logical pathway from "I see poor formatting" to "I need to add four space in front of every code line".

Actually I am finding that users still proceed to add more "poorly formatted" code even after I have edited their question myself, plus added a comment to their question to explain that it's markdown and that they need to indent code by four spaces.

My point is that such users were able to operate the Bioc Support site passably well a month ago, well enough to at least post a readable question, but now they can't.

**Comment by jmacdon** [comment]
There is no need to add four spaces in front of every code line. Right across the top of the response box are six formatting icons; **B**old, *I*talics, then four emoji looking things that you can use to insert hyperlinks, quotes, code (a block of 1s and 0s) and a blockquote box. Simply highlighting the code portion and clicking the code icon will suffice.

And I should note that the only real difference here is that a block of text that starts with > will be converted to a blue blockquote, because that's what markdown does with that input. In the past people would do essentially the same exact thing (copy/paste code) but we didn't get the annoying blue blockquote because it wasn't rendering markdown.

I would be in favor of changing the (if possible) the > to either generate code or just be ignored. Trying to have something somewhere where people who can't be bothered to read the help page would go to understand how to post to a support site is IMO a fool's errand.

**Comment by gksmyth** [comment]
@jmacdon Your mention of icons is news to me and must be browser dependent. I can tell you that there are no formating icons or emojis of any kind on the Bioconductor support web site when I use Google Chrome on Windows. All such user aids disappeared in Chrome when markdown was introduced a couple of week ago.

markdown's interpretation of ">" is not the only difference, as my post already explained. There are several characters with special meanings to both R and markdown.

Are you saying that you would be in favour of not using markdown and going back to what we had?

**Comment by jmacdon** [comment]
@gksmyth 

![image](https://user-images.githubusercontent.com/5940924/51552141-f5f7b200-1e3d-11e9-9973-832c16d898fc.png)

I see the same thing, regardless of browser. You don't see the formatting buttons?

And by 'only difference' I mean that in the past people just cut'n'pasted code, and it looked like unformatted text. If you wanted it to look reasonable you had to paste and then re-format. The only difference between then and now is that the prepending > in R code makes markdown think it is supposed to be a blockquote and so it ends up rendered as a blockquote rather than regular text.

**Comment by gksmyth** [comment]
@jmacdon Yes, that's what I'm telling you. I see no formatting buttons.

Now that you alerted me, I tried Firefox, and the buttons do appear in Firefox,

Regarding "only difference", you have left out a number of points. In past, people more often than not cut and paste code and didn't reformat, but the unformated text was still ok to read. Now the result is not readable because new-line characters are not preserved. Markdown also interprets comment characters "#" and multiplications "*" not just ">". You can see examples of this in recent posts, although I have already corrected a lot of them.

**Comment by jmacdon** [comment]
@gksmyth 

My point is not a disagreement as to how many changes have appeared, but instead a viewpoint as to how to 'fix things'. You are arguing for some sort of documentation for people to read, and pointing to (as an example) the fact that a comment section *for programmers* has something like that.

I just don't happen to think that documentation is a panacea here. Documentation is for people who are paying attention and who have a general idea of how things work. People who post on GitHub comment sections are in that group, and I would argue that a large proportion of the posters on the support site are not. So sure, we could have some documentation, but I am not sure that it will help. I mean we have this:

![image](https://user-images.githubusercontent.com/5940924/51554112-846e3280-1e42-11e9-8dbe-cf8dbfb4bc11.png)

Where the documentation for how to choose to add an answer literally surrounds the link for the answer, and people still use that to post comments. 

There is a tension here, where the markdown is nice for the cool kids who know what's up, but the square kids who can't even read help pages are going to consistently make a hash of things, and we either have to accept that fact or make it so the default for the squares is to minimize their ability to mess things up.

**Comment by mtmorgan** [comment]
@gksmyth I opened a separate issue #63 for the buttons / preview not displaying / preview slow problem... Any hints on diagnosing this from your end would be helpful.

We will add a documentation link for using the editor.

**Comment by gksmyth** [comment]
@jmacdon Yes, we are in complete agreement. You've even repeated some of the same points (e.g. the contrast between expertise on github vs bioc supp) that I made in my original post. As you would put it, markdown has increased the ability of the squares to mess things up.

So what you do suggest? Is not using markdown an option? I didn't have any say in it. Given that markdown has been introduced, don't you think that at least some documentation is better than no documentation? Even those cool kids on github seem to need documentation.

You say the alternative is to "accept" but I don't accept the current situation. I will boycott Bioconductor Support, i.e., stop answering questions so regularly, if nothing is done to improve it.

**Comment by lshep** [comment]
We will add documentation for the new editor and/or links to help pages on markdown.

**Comment by jmacdon** [comment]
@lshep 

Is it possible to make the original question box non-markdown, or does that derive from the same code that generates the answer box?

**Comment by lshep** [comment]
I'm not really in favor of having two different versions of an editor in different places - I could see this causing confusion too.  plus one of the main purposes was to realign ourselves with the original base biostars code which this would severely stray from ...  but I could look into it

**Comment by lshep** [comment]
@gksmyth  I hope to have a mini tutorial on markdown and helpful links posted to the support site early next week - when I have this set I'll also make a general news announcement announcing the editor has been changed and reference the new docs.

**Comment by gksmyth** [comment]
@lshep Thanks. The tutorial posted a few hours ago looks v helpful.

**Comment by gksmyth** [comment]
It is now more than a year later. I am sorry to say that I don't think the R markdown tutorial has made much difference. I answer Bioc Support questions most days but I almost never see any cases where a user has succeeded in using R markdown successfully. In almost all cases, the R code has been converted into a unreadable schmozzle and I have to edit the question before answering it.

It is not a requirement that users have to know Rmarkdown in order to use Bioconductor packages. My observation over the past year is that only a small proportion of users asking questions on Bioconductor Support are (1) familiar with R markdown and (2) realize that it is being used to format questions. Amongst users asking questions about limma and edgeR, the proportion is almost zero.

I am not sure that the Biocore team is entirely aware of the extent of the problem. I think that more thought is required to make the support forum easier to use.

In my opinion, users should not have to learn Rmarkdown in order to ask a question on the support site.
