### ISSUE TITLE
Remove reference to html tags from edit button "hover over text"

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/legacy.support.bioconductor.org#64]
When editing a question or answer, there are edit buttons and icons above the box, and each button has helpful explanatory text that appears when one mouses over the button.

The "hover over" text is helpful, but contains html tags that were more appropriate for the old html-based editor rather than the new markdown editor. For example, the code button "hover over" text says "pre code". In the old editor, users could indeed type those html tags into the edit box to get correctly formatted code, but in the new editor they need to type markdown instead. I understand that even the markdown will ultimately be set in html on the final page, so the html tags are ultimately correct, but that seems overly technical in this context. It would be better I think to give markdown tags "indent `...`" or else just say "Insert code".

**Comment by gksmyth** [comment]
I am going to close this issue. After some experimentation I find that one can mix html and markdown tags. In other words, it is still correct to type html tags directly into the edit box.

BTW I see that the "hover over" text matches that used on StackExchange, which presumably isn't a coincident.

**Comment by lshep** [comment]
Thanks -  I'll check the hover text and modify if necessary -  And it may take me a few days but I'll make sure we have some link to a help page or cheat sheet for markdown and an indication that the editor is default markdown now -
