### ISSUE TITLE
Can I tell who deleted a post?

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/legacy.support.bioconductor.org#74]
As a moderator, I can see deleted posts. Can I tell who deleted the post, i.e., whether the OP deleted their own question or whether it was deleted by another moderator?

My reason for asking is that a couple of Bioc Supp users have developed a pattern of asking a question and then deleting it later after it has been answered. I'd like to check that the users are doing the deleting themselves before coming to a judgement about this pattern.

**Comment by lshep** [comment]
hmm.... I don't know.  Not quite sure.  I'm not sure if deleted messages get permanently deleted or if they remain in the underlying database but filtered out.  I'll have to investigate more.

**Comment by gksmyth** [comment]
@lshep The posts that are marked as "deleted" must still be fully in the database because I can see them, including all the text and all answers and comments attached to them. They are simply shaded in pink and flagged as "(deleted)". I assume that all the forum moderators and admins can see the posts the same as I can but that they are invisible to other site visitors.

I will conclude from your reply that the site does not record who did the deleting.

**Comment by lshep** [comment]
FWIW:  I'm discussing with Natay who is helping with the Bioconductor upgrade and it seems like there will be some tracking in the database on the upgrade if it currently isn't keeping track.

**Comment by Natay** [comment]
There is a limit of 50 characters, we can increase that limit to a high number ( something like 400 or 500 characters )

**Comment by lshep** [comment]
doesn't necessarily need to be that high either -- just thinking that having 5-8 tags isn't unheard of -- and some of the package names are a little on the lengthy side.

**Comment by Natay** [comment]
The max has been bumped to 200 characters in the most recent push, we can reopen this if we need to bump it further
