### ISSUE TITLE
Change email address for Bioconductor support site

### ISSUE THREAD

**Issue by lucygarner** [Bioconductor/legacy.support.bioconductor.org#75]
Hi,

I'm sorry if this seems like a stupid question, but I can't find a way to change my login email address for the Bioconductor support site.  My old University email expired so I need to update it.

Many thanks,
Lucy

**Comment by lshep** [comment]
Currently we disabled this feature as there was a vulnerability in the code.  Could you please email webmaster@bioconductor.org with your current email and what you would like it changed to.

**Comment by Natay** [comment]
Thank you for letting us know, this is expected behavior because we have disable underscores in our markdown parser. 
We are still toying with the idea so this is not completely set in stone.

We will have the real-time preview reflect this better.
