### ISSUE TITLE
There's no way to go to the support home page from within a post

### ISSUE THREAD

**Issue by RamRS** [Bioconductor/legacy.support.bioconductor.org#77]
Usually, the image/icon on the top-left of a website takes one to the website's home page when clicked. However, the image-link on the top left of the site takes us to BioC home, not support.bioC home. There should be _some_ way to get to support.bioconductor.org from within a post.

**Comment by mtmorgan** [comment]
yes its confusing. 'Latest' takes one back to the same page as https://support.bioconductor.org.

**Comment by RamRS** [comment]
I assumed that support.bioconductor.org and support.biooconductor.org/t/Latest would have different content, but they seem to share the same sorting order and look alike. Is there any edge case where the two could be different?

**Comment by mtmorgan** [comment]
I believe that these are identical

**Comment by RamRS** [comment]
OK the, that's that for this issue. Thank you, @mtmorgan !
